
FROM node:22-alpine AS build

# Build arguments
ARG PORT
ARG MONGO_URI
ARG CLERK_SECRET_KEY
ARG CLERK_PUBLIC_KEY
ARG CLERK_SIGNING_SECRET

ENV PORT=${PORT} \
 MONGO_URI=${MONGO_URI} \
 CLERK_SECRET_KEY=${CLERK_SECRET_KEY} \
 CLERK_PUBLIC_KEY=${CLERK_PUBLIC_KEY} \
 CLERK_SIGNING_SECRET=${CLERK_SIGNING_SECRET} 

RUN npm install -g pnpm

WORKDIR /api

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

EXPOSE 8080

ENTRYPOINT [ "node", "./dist/index.js" ]